apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"flask-order-app"},"name":"flask-order-app","namespace":"default"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"flask-order-app"}},"template":{"metadata":{"annotations":{"prometheus.io/port":"8000","prometheus.io/scrape":"true"},"labels":{"app":"flask-order-app"}},"spec":{"containers":[{"env":[{"name":"PROMETHEUS_METRICS_PORT","value":"8000"}],"image":"kodekloud/flask-order-app:1","name":"flask-order-app","ports":[{"containerPort":5000,"name":"app"},{"containerPort":8000,"name":"metrics"}]}]}}}}
  creationTimestamp: "2025-02-08T06:16:24Z"
  generation: 1
  labels:
    app: flask-order-app
  name: flask-order-app
  namespace: default
  resourceVersion: "4585"
  uid: b3642ea7-a9c7-4d7a-b0a3-cc4480bc5be5
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: flask-order-app
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        prometheus.io/port: "8000"
        prometheus.io/scrape: "true"
      creationTimestamp: null
      labels:
        app: flask-order-app
    spec:
      containers:
      - env:
        - name: PROMETHEUS_METRICS_PORT
          value: "8000"
        image: kodekloud/flask-order-app:1
        imagePullPolicy: IfNotPresent
        name: flask-order-app
        ports:
        - containerPort: 5000
          name: app
          protocol: TCP
        - containerPort: 8000
          name: metrics
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2025-02-08T06:16:28Z"
    lastUpdateTime: "2025-02-08T06:16:28Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2025-02-08T06:16:24Z"
    lastUpdateTime: "2025-02-08T06:16:28Z"
    message: ReplicaSet "flask-order-app-6b54f47d97" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1